# Site settings
title: Move fast and break things
email: kjflynn@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the blog, possibly lab notebook, possibly something else, of Kaitlin Flynn's postdoc adventures in the Pat Schloss lab
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: microkaitlin
github_username:  FOXFOXFOX

# Build settings
markdown: kramdown
